services:
  image_to_album:
    build: image_to_album
    command: fastapi run image_to_album --port 8000
    ports:
      - "8000:8000"
  bff:
    build: bff
    command: fastapi run bff --port 8001
    ports:
      - "8001:8001"
