services:
  image_to_album:
    build: image_to_album
    command: fastapi run image_to_album --port 8001
    ports:
      - "8001:8001"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
        interval: 10s
        timeout: 5s
        retries: 3
    env_file:
      - .env

  bff:
    build: bff
    command: fastapi run bff --port 8000
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    depends_on:
      - image_to_album

  ui:
    build: turn_table_ui
    command: ["serve", "-l", "5173", "-s", "dist"]
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - bff

  user_data:
    build: user_data
    command: fastapi run user_data --port 8002
    ports:
      - "8002:8002"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
        interval: 10s
        timeout: 5s
        retries: 3
    env_file:
      - .env
    depends_on:
      - bff
