"""Create database.

Revision ID: 9a7c39a1f238
Revises:
Create Date: 2024-10-22 09:49:00.427892
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a7c39a1f238"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("album_uri", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("album_uri"),
        sa.UniqueConstraint("album_uri"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user_album_link_table",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("album_uri", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_uri"],
            ["albums.album_uri"],
        ),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("username", "album_uri"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_album_link_table")
    op.drop_table("users")
    op.drop_table("albums")
    # ### end Alembic commands ###
