name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image-to-album-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        cd vtt_image_to_album
        docker build .

  build-bff-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        cd vtt_bff
        docker build .

  build-ui-container:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build the Docker image
        run: |
          cd vtt_ui
          docker build .

  build-user-data-container:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build the Docker image
        run: |
          cd vtt_user_data
          docker build .
