name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image-to-album-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build the Docker image
      run: |
        cd vtt-image-to-album
        docker build .

  build-bff-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build the Docker image
      run: |
        cd vtt-bff
        docker build .

  build-ui-container:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build the Docker image
        run: |
          cd vtt-ui
          docker build .

  build-user-data-container:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build the Docker image
        run: |
          cd vtt-user-data
          docker build .
