name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          image: [ "image_to_album", "bff", "turn_table_ui", "user_data" ]
    steps:
        - uses: actions/checkout@v4
        - name: Build the Docker image
          run: |
            cd ${{ matrix.image }}
            docker build .
